### ISSUE TITLE
Package Managers

### ISSUE THREAD

**Issue by mikemelch** [mikemelch/hallie#1]
Could add more package managers. Right now hallie only supports pip but in the future it could also support apt-get, brew, and more.

**Comment by Neverbolt** [comment]
Is this already done? If it isn't I'd like to do that.

**Comment by mikemelch** [comment]
@Neverbolt Feel free to work on this feature.

**Comment by Neverbolt** [comment]
Put up a PR with #8

**Comment by mikemelch** [comment]
#8 resolves this issue.
